### ISSUE TITLE
Expose MDC logback property map in LogEvent

### ISSUE THREAD

**Issue by lcardito** [Hakky54/log-captor#13]
**Is your feature request related to a problem? Please describe.**
We need to test that we're correctly passing down the MDC context into executors and completable futures

**Describe the solution you'd like**
Expose the MDC property map in the `LogEvent` object so that we can extract the map in our test assertions

**Describe alternatives you've considered**
None so far 😞 

**Additional context**
The `ILoggingEvent` interface from logback exposed the MDC property map via a get method.

```
Map<String, String> getMDCPropertyMap();
```

Would be awesome if we could populate the `LogEvent` object with a copy of the MDC map from the original event 🥺 

Would love to get together a PR if I can help 😄

**Comment by Hakky54** [comment]
Hi @lcardito 

Thank you for using LogCaptor and creating this feature request.
The MDC property is already available in the `LogEvent` since LogCaptor version `2.6.0`. See here for the PR: https://github.com/Hakky54/log-captor/pull/10

You can access it with the following snippet:
```
Map<String, String> diagnosticContext = logCaptor.getLogEvents().get(0)
        .getDiagnosticContext();
```

We decided to not use the `MDC` abbreviation, which means managed diagnostic context. Instead we decided to name it diagnostic context. This feature is just release today, but it should already be available in maven central.

**Comment by lcardito** [comment]
Woooo! Thanks folks! Will try that out tomorrow first thing!

**Comment by Hakky54** [comment]
Great, I am closing this issue. If you have any other requests feel free to open a new issue 😄

**Comment by lcardito** [comment]
Aaaannnd that worked as expected! Thanks again! 💯
