### ISSUE TITLE
There appears to be a classloading problem when using LogCaptor with `@QuarkusTest` test classes

### ISSUE THREAD

**Issue by SanderSmee** [Hakky54/log-captor#32]
**Describe the bug**
When using logcaptor with quarkus in a test annotated with `@QuarkusTest`, an exception is thrown when creating a `LogCaptor` instance using the factory method(s). I followed the steps to exclude the quarkus slf4j implementation per the documentation, but now the error is `SLF4J Logger implementation should be of the type [ch.qos.logback.classic.Logger] but found [ch.qos.logback.classic.Logger].` from `ValidationUtils.java`.

**To Reproduce**
1. I created a MRE at this repository https://github.com/SanderSmee/mre-logcaptor-quarkus . It contains 2 tests, one with and one without `@QuarkusTest` to identify the problem

**Expected behavior**
A correct instantiation of a `LogCaptor` instance, so logging can be captured.

**Environmental Data:**
 - Java Version : openjdk version "11.0.13" 2021-10-19 LTS
 - Maven Version
 - Gradle Version: 7.3.3
 - OS : MacOS 21.2, MacBook M1Pro

**Additional context**
I'm aware of the classloading things that quarkus does when using tests with `@QuarkusTest`. So it's possible the solution to this problem lies with quarkus.

**Comment by Hakky54** [comment]
Hi Sander, 

Thank you for raising this issue. The sample project is very helpful to easily reproduce the issue. The exception message you are getting is confusing and should be improved. I will create a change in the library for that specific use case.

LogCaptor needs Logback to capture logs and in your case it is already using that so it should not raise the exception, but this exception is being caused because of a different reason. The Logger of GreetingResource is created by `jdk.internal.loader.ClassLoaders$AppClassLoader` while all classes within the test even LogCaptor is created by `io.quarkus.bootstrap.classloading.QuarkusClassLoader` because of the `@QuarkusTest` annotation. It will try to cast the captured Logger which is of the type `ch.qos.logback.classic.Logger` to `ch.qos.logback.classic.Logger` but it fails because those to objects are totally different classes to the JVM because they are created by different classloaders.

I have tried to resolve this issue on the library side by changing the classloader order, and also used reflection to specify which classloader the library should use and some other methods but I could not resolve it. I would advise to create the same issue at https://github.com/quarkusio/quarkus The might know how to resolve this classloader issue as the annotation `@QuarkusTest` is causing this issue.

For the time being you can use [ConsoleCaptor](https://github.com/Hakky54/console-captor), which is also created by me. That library captures everything from the console output. If you make sure to forward all of your logs to the console by using slf4j-simple than console captor can easily capture those logs. You can enable it by adding the following imports to your build.gradle file:
```
testImplementation('io.github.hakky54:consolecaptor:1.0.2')
testImplementation('org.slf4j:slf4j-simple:1.7.36')
```

```java
@Path("/hello")
public class GreetingResource {
    Logger logger = LoggerFactory.getLogger(GreetingResource.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        logger.info("Hello");

        return "Hello RESTEasy";
    }
}
```

```java
@QuarkusTest
class QuarkusTestTest {

    @Test
    void captureLogs() {
        try(ConsoleCaptor consoleCaptor = new ConsoleCaptor()) {
            new GreetingResource().hello();

            List<String> errorOutput = consoleCaptor.getErrorOutput();

            assertEquals(1, errorOutput.size());
            assertTrue(errorOutput.get(0).contains("Hello"));
        }
    }

}
```

So my advise is to raise this issue at Quarkus and in the mean while you can try using ConsoleCaptor till Quarkus can provide a solution. Hope this alternative solution is something which is useful for you.

**Comment by SanderSmee** [comment]
Thank you for looking into this, and the effort in trying to solve it in LogCaptor. 
In my own investigation I did see where the exception was thrown, and that the classes were from different classloaders. Your conclusions match the suspicion I had at that point: it's a quarkus thing that is not easily solved. Further research shows that `@QuarkusTest` is known to do advanced things with classloading, and also disrupts usage of other junit5  extensions (e.g. junit-kafka).

Also thanks for the suggestion of ConsoleCaptor. I'll check how I can make that work in my current situation.

**Comment by LunaticoCR** [comment]
Sadly, this issue still exists today in Quarkus. ☹️

**Comment by LunaticoCR** [comment]
Thank you very much @Hakky54 ! I'll keep an eye on the Quarkus issue too.
