### ISSUE TITLE
Not compatible with log4j2 2.17.2

### ISSUE THREAD

**Issue by lvm-5** [Hakky54/log-captor#35]
**Describe the bug**
It's not compatible with log4j2 2.17.2. It happen after log4j2 broke compatibility with slf4j binding.

**To Reproduce**
1. Migrate to log4j2 2.17.2
2. Exception at Junit5 testing:
java.lang.ExceptionInInitializerError
Caused by: java.lang.ClassCastException: org.apache.logging.slf4j.SLF4JLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext

**Expected behavior**
No exception

**Screenshots**

**Environmental Data:**
 - Java Version: 8
 - Maven Version
- OS (Windows/Linux/MacOS): wsl(Ubuntu)

**Additional context**
Log4j2 supplied with new sfl4j adapter to fix compatibility issue: log4j-slf4j-impl and log4j-slf4j18-impl, but replacing log4j-to-slf4j adapter with them didn't work.

**Comment by lvm-5** [comment]
Hello @Hakky54,

I've added dependency as you suggested, but it didn't solved the issue. Pay your attention logcaptor still use log4j-to-slf4j dependency:
![image](https://user-images.githubusercontent.com/14575180/177709957-fb6b1ad5-2952-4055-9d54-4babd7190aca.png)

The issue was gone when I've excluded log4j-to-slf4j from logcaptor configuration:
```xml
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j18-impl</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.hakky54</groupId>
      <artifactId>logcaptor</artifactId>
      <version>${logcaptor.version}</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-to-slf4j</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
Bellow a result of such exclusion.
![image](https://user-images.githubusercontent.com/14575180/177710304-e18b6e3f-6d37-4c34-92d1-1629e5eb6923.png)

**Comment by lvm-5** [comment]
Hello @Hakky54,

I've added dependency as you suggested, but it didn't solve the issue. Pay your attention logcaptor still use log4j-to-slf4j dependency:
![image](https://user-images.githubusercontent.com/14575180/177718034-c6539c42-269a-4d5c-bd38-a82b372a9257.png)

**Comment by Hakky54** [comment]
It is strange that the same error is still occuring. In the reference project it is working, so i would be expecting the same for your case. But maybe i missed something. 

Would it be possible for you to create a very minimalistic GitHub repo demonstrating the issue what you have. In that way i can easily debug your issue while having your setup.

**Comment by Hakky54** [comment]
Hi @lvm-5 

Sorry for my late reply. I was at holiday and today I came back and got a better chance to analyse the situation. 
In my earlier example I have used the `log4j-slf4j18-impl` incorrectly so the solution which I gave was not good enough. Using LogCaptor alongside with `log4j-slf4j18-impl` is troublesome as it redirects SLF4J logs to Log4J because of the SLF4J implementation which is shipped alongside with `log4j-slf4j18-impl`. LogCaptor uses Logback to to capture the logs, however using LogCaptor with `log4j-slf4j18-impl` will not work as it will have 2 SLF4J implementations on the classpath. Excluding one or the other will break the functionality of either logging or capturing logs. This issue cannot be resolved in my opinion. For this special kind of use cases I have introduced some time ago [ConsoleCaptor](https://github.com/Hakky54/console-captor) which has limited features compared to LogCaptor but you will be able to test your logs, log level etc. ConsoleCaptor can capture console output and it will return a list. You just need to make sure that your logs are appended to the console during your tests.

What you need to do is:

2. Add ConsoleCaptor to your project:
```xml
<dependency>
    <groupId>io.github.hakky54</groupId>
    <artifactId>consolecaptor</artifactId>
    <version>1.0.2</version>
    <scope>test</scope>
</dependency>
```

2 Add log4j2.xml file to test resources:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
        </Console>
    </Appenders>
    <Loggers>
        <Root level="debug">
            <AppenderRef ref="Console" />
        </Root>
    </Loggers>
</Configuration>
```

4. Example FooService class 
```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FooService {

    private static final Logger LOGGER = LoggerFactory.getLogger(FooService.class);

    public void hello() {
        LOGGER.info("Hello there friend!");
    }

    public static void main(String[] args) {
        new FooService().hello();
    }

}
```

5. Add your test class
```
import nl.altindag.console.ConsoleCaptor;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class FooServiceTest {

    @Test
    void sayHello() {
        ConsoleCaptor consoleCaptor = new ConsoleCaptor();

        FooService fooService = new FooService();
        fooService.hello();

        assertThat(consoleCaptor.getStandardOutput()).hasSize(1);
        assertThat(consoleCaptor.getStandardOutput().get(0)).contains("Hello there friend!");
    }

}
```

I have created an example project here which you can analyse: https://github.com/Hakky54/java-tutorials/tree/main/console-captor-examples/console-captor-with-log4j-slf4j18
