### ISSUE TITLE
Does this project target Log4J API 1.7?

### ISSUE THREAD

**Issue by Zordid** [Hakky54/log-captor#38]
**Describe the bug**
When putting log-captor to my project, I immediately get the classic org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j exception.

BUT: excluding log4j-slf4j-impl from the test scope, turns thing around so that now NO logger implementation is found:
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/q163557/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.11/4741689214e9d1e8408b206506cbe76d1c6a7d60/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

SLF4J Logger implementation should be of the type [ch.qos.logback.classic.Logger] but found [org.slf4j.helpers.NOPLogger].

My project is now working with Log4J2 - could it be that this log-captor is still using the 1.7 API??

**Comment by Hakky54** [comment]
Hi Olaf,

That error is indeed the classic error and pretty annoying, but it should be resolvable. LogCaptor is still using SLF4J v1.7.x but I am planning to bump it to v2.x.x However LogCaptor is compatible with Log4J2 and currently also tested with the latest version `2.19.0`

Looking at your issue you have `log4j-slf4j-impl` on your classpath. That dependency relies on SLF4J v1.7.x and is compatible with LogCaptor.  Excluding `log4j-slf4j-impl` from your classpath during the test phase should work as I have a working example here: https://github.com/Hakky54/java-tutorials/blob/main/log-captor-examples/log-captor-with-slf4j-log4j/pom.xml

So I have the feeling that another dependency in your project might be causing this issue. If another dependency has a transitive dependency on SLF4J v2.x.x than it will fail to captor the logs and give you indeed those warnings. Can you validate that by running a dependency tree and check which SLF4J version iss being used?

**Comment by Zordid** [comment]
Yes, and the move to SLF4J 2.x.x is deliberate... :-( I cannot get this out as my main logging library is io.github.microutils:kotlin-logging-jvm:3.0.0

They moved from API 1.7 to API 2.x - and thus I get into problems. Formerly I used uk.org.lidalia:slf4j-test:1.2.0 to test my logs in unit tests, but that one is very, very old and also cannot work with API 2.x.

To be honest, this whole world of Log4J 1, 2, API versions, implementations, bindings, etc is completely frustrating me. :-/

**Comment by Hakky54** [comment]
No worries, I understand your frustration. It is awfull that there are so many logging frameworks and you are getting this issue because other dependencies which are using different versions.

My overall suggestion for your project would be to make sure you use 1 logging framework. Either SLF4J or Log4J2 and redirect all logs to that logging framework. For this you need to analyse your dependency tree. And next to that make sure you are using one specific version by excluding the transitive dependencies and by specifiying it in the dependency management section (if you are using maven). But that is something which can take some time to refactor and not needed to just get LogCaptor working.

The main reason why I didn't upgraded SLF4J for LogCaptor to version v2.x.x is because Log4j2 maintainers didn't released an adapter for it yet. They have one for SLF4J v1.7.x which I am using, see here for the dependency: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-to-slf4j/2.19.0

There are couple of things what you can do:
1.  Exclude SLF4J from `kotlin-logging-jvm` during the test phase. In that way LogCaptor will use SLF4J version 1.7.x I tried this in the past, but could not get it working. So I am unfortunately not able to provide you examples...
2. Add `ch.qos.logback:logback-classic:1.4.3` and `org.apache.logging.log4j:log4j-to-jul:2.19.0` as a test dependency. Logback is being used by LogCaptor as the engine to capture logs. This version of Logback is compatible with SLF4J v2.x.x and the log4j-to-jul will forward your own logs to java util logging which LogCaptor is able to capture regardless of the SLF4J version. In that way you don't need an adapter for Log4J2 for SLF4J v2.x.x and it should just work with the java util logging adapter.

Can you give it a try and share your results here? I am also curious which option you would prefer 😄

**Comment by Zordid** [comment]
Oh gosh... I don't even know the differences between slf4j and log4j2... this is all so, so confusing. Sorry to bother you with this...

I do use Gradle, not Maven. All I did to start my logging is to rely on kotlin-logging-jvm, which adds this transitive dependency: slf4j-api:2.0.1
When you start the application with this single dependency, you get this warning:
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

Sounds reasonable, as you need to also add logging implementations, aka providers.
So I add: org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0 to my dependencies.
This leads to:
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

Ok, I do as instructed - adding org.apache.logging.log4j:log4j-core:2.19.0 to my dependencies.
We are now at:
```
    implementation("io.github.microutils:kotlin-logging-jvm:3.0.0")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0")
    implementation("org.apache.logging.log4j:log4j-core:2.19.0")
```

This is the first working solution. I do not really know how I would name this. Am I using Log4J2 now? Or SLF4J? API 1.7 or 2.0.x? Of what. Here the confusion is already happening...


Now - I want to write a unit test, making sure some code part logs an error.
I now add
```
testImplementation("io.github.hakky54:logcaptor:2.7.10")
```

And now my code crashes with this:
`org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j`

Okay, we now have a conflicting dependency, right? I have NO clue what log4j-slf4j-impl vs log4j-to-slf4j are. We do people come up with such confusing names... *grrrr* And where the hack is my second "2" as in log4j-slf4j2-impl??

I try to exclude one dependency at test runtime using
```
configurations.testRuntimeOnly {
    // don't allow two log4j implementations to be present at test time
    exclude(module = "log4j-slf4j-impl")
}
```

This does not change anything.

So I try your second approach, adding:
```
    testImplementation("io.github.hakky54:logcaptor:2.7.10")
    testImplementation("ch.qos.logback:logback-classic:1.4.3")
    testImplementation("org.apache.logging.log4j:log4j-to-jul:2.19.0")
```

Which changes behaviour to this problem:
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [org.apache.logging.slf4j.SLF4JServiceProvider@7fc95ed5]
SLF4J: Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@1771617f]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual provider is of type [org.apache.logging.slf4j.SLF4JServiceProvider@7fc95ed5]

It feels I am getting closer, but still I am not there... now that there are TWO implementations and the "wrong" one gets picked, testing the logging still does not work.

Why on earth is logging such an overly complex thing? Working through Stack Overflow is a nightmare with all those wrong and outdated answers... :-(

Thanks a lot for trying to help!

**Comment by Hakky54** [comment]
Yes, you are definitely getting closer but we still need to do some minor changes. Thank you by the way for explaining all the stepds you did, it gives me a better unstanding of what you did and what went wrong. I would recommend just reading the top answer of this stackoverflow topic, it might be helpful: [What is the difference between Log4j, SLF4J and Logback?](https://stackoverflow.com/questions/39562965/what-is-the-difference-between-log4j-slf4j-and-logback)

I will shortly explain the logging frameworks as far as I know. In the beginning the JDK shipped with a default logging utility called Java Util Logging also known as JUL. JUL did the job and worked well, but for others it did miss some features. So the community started creating their own logging utilities like SLF4J, Log4J2 and others which I am not aware of. These logging utilities provided api's which had methods like `log.info()` but did not do actually anything. You needed a logging binding also known as logging implementation which did actually do something when a method on the logger was called. The idea was that everyone could develop a custom implementation for their own needs having different ways of handling logs.

I won't explain you the full detail of all of those implementations and the capabilities of it, but I just want to tell you so that you are aware of it. The community has accepted the logging utilities and currently the two biggest ones are SLF4J and Log4J2 and they have their own logging implementation also available.

Coming back to your issue, I think it is pretty easy to solve as it is now clear for me that you don't need Log4J2. It seems like you added it by accident because the warning message of SLF4J was not clear enough. I would suggest the following changes to your project:

Can you remove these parts in your gradle build:
```
implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0")
implementation("org.apache.logging.log4j:log4j-core:2.19.0")
testImplementation("org.apache.logging.log4j:log4j-to-jul:2.19.0")

configurations.testRuntimeOnly {
    // don't allow two log4j implementations to be present at test time
    exclude(module = "log4j-slf4j-impl")
}
```

You can keep the following dependency:
```
testImplementation("ch.qos.logback:logback-classic:1.4.3")
```

Can you adjust the logcaptor dependency declaration:
```
testImplementation("io.github.hakky54:logcaptor:2.7.10"){
    exclude("ch.qos.logback", "logback-classic")
    exclude("org.apache.logging.log4j", "log4j-to-slf4j")
}
```

So your resulting gradle build configuration should have the following dependencies:
```
implementation("io.github.microutils:kotlin-logging-jvm:3.0.0")

testImplementation("ch.qos.logback:logback-classic:1.4.3")
testImplementation("io.github.hakky54:logcaptor:2.7.10"){
    exclude("ch.qos.logback", "logback-classic")
    exclude("org.apache.logging.log4j", "log4j-to-slf4j")
}
```

Can you retry and share your results?

**Comment by Zordid** [comment]
Hi again! Thanks for all your time and effort, I really appreciate this!

So. Your last configuration does the job, but only for test side. Everything runs smooth there and LogCaptor can do its job.

But... on the production side, when I run my product, it complains again about no providers for logging:
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

This is exactly where I started: using the main logging util dependency kotlin-logging which does not include any providers. 

If I only knew now which provider/dependency I can add to the implementation dependencies without disturbing the test side again...

**Comment by Hakky54** [comment]
So `kotlin-logging-jvm` provides `slf4j-api` and it is up to you which slf4j implementation you want to add to your project. For hobby projects I prefer to use `org.slf4j:slf4j-simple` which just prints the logs to the console, hoewever for bigger projects or enterprise projects I prefer to use Logback which is capable of doing more advanced stuff like appending the logs to a file and also to the console and other features, see here for the documentation: https://logback.qos.ch/manual/index.html

If you want to use `org.slf4j:slf4j-simple` than your configuration would be:
```
implementation("io.github.microutils:kotlin-logging-jvm:3.0.0")
implementation("org.slf4j:slf4j-simple:2.0.3")

testImplementation("ch.qos.logback:logback-classic:1.4.3")
testImplementation("io.github.hakky54:logcaptor:2.7.10"){
    exclude("ch.qos.logback", "logback-classic")
    exclude("org.apache.logging.log4j", "log4j-to-slf4j")
}

configurations.testRuntimeOnly {
    exclude(module = "slf4j-simple")
}
```

If you want to use logback, than your configuration would be:
```
implementation("io.github.microutils:kotlin-logging-jvm:3.0.0")
implementation("ch.qos.logback:logback-classic:1.4.3")

testImplementation("io.github.hakky54:logcaptor:2.7.10"){
    exclude("ch.qos.logback", "logback-classic")
    exclude("org.apache.logging.log4j", "log4j-to-slf4j")
}
```

This should do the trick for you and resolve the last issue.
